### ISSUE TITLE
ewelink-api-release_2.0.0 ArpTable DevicesCachejson result as json Enhancement

### ISSUE THREAD

**Issue by scInvest** [skydiver/ewelink-api#57]
I've been testing your ewelink-api-release_2.0.0 zeroconf, beside windows compability problems I've find out that storing, `ArpTable` and `DevicesCache` to files creates a lot of troubles. Would it be possible to get `saveDevicesCache();` and `Zeroconf.saveArpTable` result after await, eg. via callback? Insted of storing them to file, and then load, and then use js objects.

**Comment by skydiver** [comment]
Hello @scInvest 

To get the arp table, you can just do:
```
const Zeroconf = require('ewelink-api/classes/Zeroconf');
const arp = await Zeroconf.getArpTable('192.168.5.1');
```

To get devices data:
```
const connection = new ewelink({
  email: 'user',
  password: 'pass',
});
const devices = connection this.getDevices();
```

Then you can use `arp` and `devices` to connect.

**Comment by ttz642** [comment]
````await connection.saveDevicesCache();````
works, but:
````const arp = await Zeroconf.getArpTable('192.168.8.1');````
returns nothing...
Can you show example of the json structure saved in the file?

**Comment by skydiver** [comment]
@ttz642:

There was a problem with the arp package who was fixed and merged today.

Here is the expected format:

```
[
  {
    "ip": "192.168.100.1",
    "mac": "aa:bb:cc:dd:ee:ff"
  },
  {
    "ip": "192.168.100.2",
    "mac": "aa:bb:cc:dd:ee:ee"
  }
]
```

**Comment by ttz642** [comment]
> There was a problem with the arp package who was fixed and merged today.

I just removed the release 2 branch I'd installed and re-installed the master branch which is the 2.0.0 release (including fix I assume).

Still doesn't work (for me).

I'm using ubuntu 18.04 (will update to 20.04 when released).

**Comment by ttz642** [comment]
I haven't looked through the code just yet but I'm guessing the ArpTable is used to map the mac id to the ip.

What your really after is what is the ip address of the device id, I assume your looking for the mac address in the device cache then looking for the ip address in the ArpTable.

What you really want is a table mapping device id's to ip addresses.

The following linux command:
```
avahi-browse -arlcfp | grep -P '^=' |  grep "eWeLink" \
	| pcre2grep -o2 -o1 -i --om-separator='|' 'local;eWeLink_(1000[0-9a-f]{6}).local;(192.168.1\..+);8081;' \
	| gawk -F '|' -e 'BEGIN{print "{";li="";}{printf li"  \"%s\": \"%s\"",$2,$1;li=",\n";}END{print "\n}";}' \
	> deviceip-table.json
```
creates the json file deviceip-table.json, which contains:
```
{
  "1000xxxxxx": "192.168.1.233",
  "1000xxxxxx": "192.168.1.220",
  "1000xxxxxx": "192.168.1.238",
  "1000xxxxxx": "192.168.1.237",
  "1000xxxxxx": "192.168.1.202",
  "1000xxxxxx": "192.168.1.249",
  "1000xxxxxx": "192.168.1.227"
}
```
Therefore if the json is read into an array deviceIP all we need to do to resolve the ip address is use the device id, ie:
`deviceIP[<deviceid>]
`
BTW: avahi-browse works best when the devices are disconnected from the WAN as the devices broadcast their availability more often.
